pub const ADJECTIVES: [&str; 1023] = [
    "able", "absent", "absurd", "academic", "aching", "acidic", "active", "actual", "adept",
    "admired", "adored", "advanced", "aerobic", "afraid", "aged", "agile", "agitated", "ajar",
    "alarmed", "alarming", "alert", "alive", "amazing", "ample", "amusing", "anchored", "ancient",
    "angelic", "angry", "animated", "annual", "another", "antique", "anxious", "any", "apart",
    "apt", "aquatic", "arctic", "arid", "aromatic", "artistic", "ashamed", "asleep", "assured",
    "atomic", "attached", "austere", "average", "awake", "aware", "awesome", "awful", "awkward",
    "babyish", "back", "bad", "baggy", "bare", "barren", "basic", "belated", "beloved", "best",
    "better", "big", "bitter", "black", "bland", "blank", "blaring", "bleak", "blind", "blond",
    "blue", "bogus", "boiling", "bold", "bony", "boring", "bossy", "both", "bouncy", "bowed",
    "brave", "brief", "bright", "brisk", "broken", "bronze", "brown", "bruised", "bubbly", "bulky",
    "bumpy", "buoyant", "burly", "busy", "buttery", "buzzing", "calm", "candid", "canine",
    "capable", "capital", "carefree", "careful", "caring", "casual", "cautious", "certain",
    "cheap", "cheery", "chief", "chilly", "chronic", "chubby", "civil", "classic", "clean",
    "clear", "clever", "closed", "cloudy", "clueless", "clumsy", "coarse", "cold", "colonial",
    "common", "compact", "complete", "complex", "confused", "content", "cooked", "cool", "copper",
    "corny", "correct", "corrupt", "costly", "cotton", "crafty", "crazy", "creamy", "creative",
    "creepy", "crisp", "critical", "crooked", "crowded", "cruel", "cuddly", "cultural", "curious",
    "curly", "current", "curvy", "cute", "daily", "damaged", "damp", "dapper", "daring", "dark",
    "darling", "deadly", "dearest", "decent", "decimal", "deep", "defeated", "defiant", "delayed",
    "delicate", "dense", "dental", "detailed", "devoted", "digital", "dim", "dimpled", "direct",
    "dirty", "dismal", "distant", "distinct", "diverse", "divine", "dizzy", "domestic", "dopey",
    "doting", "double", "drab", "drafty", "dramatic", "dreary", "droopy", "dry", "dual", "dull",
    "dumb", "dusty", "dutiful", "dynamic", "each", "eager", "early", "earnest", "easy", "economic",
    "edible", "educated", "elastic", "elated", "elderly", "elegant", "eligible", "eminent",
    "empty", "endless", "enormous", "enraged", "entire", "envious", "equal", "eternal", "ethical",
    "ethnic", "even", "every", "evident", "evil", "exact", "exalted", "excited", "exciting",
    "existing", "exotic", "expert", "extra", "failing", "faint", "fair", "fake", "familiar",
    "famous", "fancy", "far", "faraway", "fast", "fat", "fatal", "fearful", "federal", "feisty",
    "feline", "female", "fertile", "festive", "fickle", "fierce", "filthy", "final", "fine",
    "firm", "first", "fiscal", "fitting", "fixed", "flaky", "flashy", "flat", "flawed", "fleeting",
    "flimsy", "floral", "flowery", "fluent", "fluffy", "fluid", "flying", "focused", "fond",
    "foolish", "foreign", "forked", "formal", "forward", "fragile", "frail", "frank", "frayed",
    "free", "French", "fresh", "frigid", "frilly", "frizzy", "front", "frosty", "frozen", "frugal",
    "fruitful", "full", "funny", "furious", "fussy", "future", "fuzzy", "gaseous", "general",
    "generous", "gentle", "genuine", "giant", "giddy", "gifted", "gigantic", "giving", "glad",
    "glaring", "glass", "gleeful", "global", "gloomy", "glossy", "glum", "golden", "good",
    "graceful", "gracious", "grand", "grave", "gray", "great", "greedy", "green", "grim", "grimy",
    "grizzled", "gross", "grouchy", "grounded", "growing", "grown", "grubby", "grumpy", "guilty",
    "gummy", "hairy", "half", "handy", "happy", "hard", "harmful", "harsh", "hasty", "hateful",
    "healthy", "hearty", "heavy", "hefty", "helpful", "helpless", "hidden", "hideous", "high",
    "historic", "hoarse", "hollow", "holy", "homely", "honest", "honored", "hopeful", "hostile",
    "hot", "huge", "human", "humble", "humming", "hungry", "hurtful", "husky", "icky", "icy",
    "ideal", "idiotic", "idle", "idolized", "ill", "illegal", "immense", "impish", "impure",
    "inborn", "indirect", "indolent", "infinite", "insane", "inside", "instant", "intent",
    "intimate", "intrepid", "involved", "iron", "ironclad", "isolated", "itchy", "jaded", "jagged",
    "jaunty", "jealous", "jittery", "joint", "jolly", "jovial", "joyful", "joyous", "judicial",
    "juicy", "jumbo", "jumpy", "junior", "just", "keen", "key", "kind", "kindly", "klutzy",
    "knobby", "knotty", "knowing", "known", "kooky", "kosher", "labor", "lame", "lanky", "large",
    "late", "lavish", "lawful", "lazy", "leading", "leafy", "lean", "left", "legal", "light",
    "likable", "likely", "limited", "limp", "limping", "linear", "lined", "liquid", "little",
    "lively", "livid", "local", "logical", "lone", "lonely", "long", "loose", "lost", "loud",
    "lovable", "lovely", "loving", "low", "loyal", "lucky", "luminous", "lumpy", "lunar",
    "lustrous", "luxury", "mad", "magical", "main", "majestic", "major", "male", "mammoth", "many",
    "marine", "married", "massive", "master", "mature", "maximum", "meager", "mealy", "mean",
    "measly", "meaty", "medium", "meek", "mellow", "melodic", "mental", "mere", "merry", "messy",
    "middle", "mild", "milky", "mindless", "minimal", "minor", "minty", "miserly", "misty",
    "mixed", "mobile", "modern", "modest", "moist", "monthly", "moral", "mortal", "mostly",
    "muddy", "muffled", "mundane", "murky", "mushy", "musty", "muted", "mutual", "naive", "naked",
    "narrow", "nasty", "national", "natural", "naughty", "nautical", "naval", "near", "nearby",
    "neat", "needy", "nervous", "neutral", "new", "next", "nice", "nifty", "nimble", "nippy",
    "noble", "noisy", "nonstop", "normal", "nosy", "notable", "noted", "novel", "noxious",
    "nuclear", "numb", "obedient", "obese", "oblong", "obvious", "odd", "oddball", "offbeat",
    "oily", "old", "only", "open", "optimal", "opulent", "oral", "orange", "orderly", "organic",
    "ornate", "ornery", "other", "our", "outdoor", "outer", "outgoing", "outside", "oval",
    "overdue", "paid", "pale", "paltry", "parched", "parental", "partial", "pastel", "patient",
    "peaceful", "peculiar", "peppery", "perfect", "perfumed", "perky", "personal", "pesky",
    "petty", "phony", "piercing", "pink", "pitiful", "plain", "plastic", "playful", "pleasant",
    "pleased", "plump", "plush", "poetic", "pointed", "poised", "polished", "polite", "poor",
    "popular", "portly", "posh", "positive", "possible", "postwar", "potable", "precious",
    "pregnant", "present", "pretty", "previous", "prickly", "primary", "prime", "pristine",
    "private", "prize", "probable", "profuse", "proper", "proud", "proven", "prudent", "public",
    "pungent", "puny", "pure", "purple", "pushy", "putrid", "puzzled", "puzzling", "quaint",
    "queasy", "quick", "quiet", "quirky", "racial", "radiant", "radical", "ragged", "rainy",
    "random", "rapid", "rare", "rash", "raw", "ready", "real", "recent", "red", "regal", "regular",
    "related", "reliable", "relieved", "remote", "renewed", "resolved", "restful", "retail",
    "retired", "rich", "right", "rigid", "ringed", "ripe", "rising", "risky", "rival", "roasted",
    "robotic", "robust", "romantic", "rosy", "rotten", "rough", "round", "rowdy", "royal",
    "rubbery", "ruddy", "rude", "rundown", "runny", "rural", "rusty", "sad", "safe", "salty",
    "same", "sandy", "sane", "scaly", "scarce", "scared", "scary", "scented", "scrawny", "second",
    "secret", "secure", "self", "selfish", "separate", "serene", "serious", "several", "severe",
    "sexual", "shabby", "shadowy", "shady", "shallow", "sharp", "sheer", "shiny", "shocked",
    "shoddy", "short", "showy", "shrill", "shy", "sick", "silent", "silky", "silly", "silver",
    "similar", "simple", "sinful", "single", "skilled", "skinny", "sleepy", "slight", "slimy",
    "slippery", "slow", "slushy", "small", "smart", "smoggy", "smooth", "smug", "snappy", "sneaky",
    "snoopy", "sociable", "social", "soft", "soggy", "solar", "solid", "somber", "some", "sore",
    "sorry", "soulful", "soupy", "sour", "spare", "sparse", "spatial", "special", "specific",
    "speedy", "spicy", "spiffy", "splendid", "spooky", "spotted", "spry", "square", "squeaky",
    "squiggly", "stable", "staid", "stained", "stale", "starchy", "stark", "starry", "static",
    "steady", "steel", "steep", "sticky", "stiff", "still", "stingy", "stormy", "strange",
    "strict", "striking", "striped", "strong", "studious", "stunning", "stupid", "sturdy",
    "stylish", "subdued", "subtle", "suburban", "sudden", "sugary", "sunny", "super", "superb",
    "superior", "supreme", "sure", "svelte", "sweaty", "sweet", "swift", "symbolic", "tactical",
    "tall", "tame", "tan", "tangible", "tart", "tasty", "taut", "tedious", "teeming", "tempting",
    "tender", "tense", "tepid", "terrible", "terrific", "testy", "thankful", "that", "these",
    "thick", "thin", "thirsty", "this", "thorny", "those", "thrifty", "tidy", "tight", "timely",
    "tinted", "tiny", "tired", "torn", "total", "tough", "toxic", "tragic", "trained", "tribal",
    "tricky", "trifling", "trim", "trivial", "trusted", "trusting", "tubby", "twin", "typical",
    "ugly", "ultimate", "unable", "unaware", "uncommon", "under", "uneasy", "uneven", "unfit",
    "unhappy", "uniform", "unique", "united", "unkempt", "unknown", "unlined", "unlucky", "unpaid",
    "unripe", "unruly", "unseen", "unsteady", "unsung", "untidy", "untimely", "untried", "untrue",
    "unused", "unusual", "upbeat", "upper", "upright", "upset", "urban", "urgent", "usable",
    "used", "useful", "useless", "usual", "utter", "vacant", "vague", "vain", "valid", "vapid",
    "vast", "velvety", "vengeful", "verbal", "vertical", "very", "vibrant", "vicious", "vigilant",
    "vigorous", "violent", "violet", "virtual", "visible", "visual", "vital", "vivid", "vocal",
    "void", "volatile", "wan", "warlike", "warm", "warped", "wary", "wasted", "watery", "wavy",
    "weak", "wealthy", "weary", "webbed", "weekly", "weepy", "weighty", "weird", "welcome", "well",
    "western", "wet", "which", "white", "whole", "whopping", "wicked", "wide", "wiggly", "wild",
    "willing", "wilted", "winding", "windy", "winged", "wiry", "wise", "witty", "wobbly", "woeful",
    "wooden", "woozy", "wordy", "working", "worldly", "worn", "worried", "worse", "worst",
    "worthy", "wrong", "wry", "yawning", "yearly", "yellow", "young", "yummy", "zany", "zealous",
    "zesty", "zigzag",
];
