pub const NOUNS: [&str; 1023] = [
    "able", "alarm", "alley", "ankle", "apple", "arch", "asset", "aunt", "axis", "bacon", "bag",
    "ball", "bamboo", "bar", "base", "beach", "beef", "belt", "bid", "bike", "bird", "birth",
    "black", "blade", "blame", "blast", "bless", "blush", "body", "boil", "bonus", "boost",
    "border", "boss", "bottom", "bounce", "brain", "brand", "brass", "brave", "brick", "bright",
    "brisk", "bronze", "broom", "brush", "buddy", "bulb", "bulk", "burst", "butter", "buzz",
    "cabin", "cable", "call", "calm", "camp", "candy", "cannon", "carbon", "card", "cargo",
    "carry", "cart", "case", "cash", "casino", "castle", "cat", "catch", "cattle", "cause",
    "chair", "chaos", "charge", "chase", "check", "chef", "chest", "child", "cigar", "circle",
    "clap", "claw", "clay", "clerk", "click", "cliff", "climb", "clock", "close", "cloud", "club",
    "clutch", "coach", "coast", "code", "coffee", "coin", "come", "comic", "cook", "copper",
    "coral", "core", "cost", "cotton", "couch", "course", "cousin", "craft", "crash", "crawl",
    "creek", "crew", "cross", "crowd", "cruise", "curve", "cushion", "cycle", "dad", "dawn",
    "deal", "decrease", "deer", "degree", "delay", "deliver", "demand", "dentist", "deny",
    "depend", "deputy", "desert", "desk", "detail", "detect", "develop", "diagram", "diamond",
    "diary", "diesel", "diet", "differ", "dignity", "dinner", "direct", "dirt", "disease", "dish",
    "distance", "doctor", "document", "dose", "dove", "draft", "dragon", "draw", "dream", "drill",
    "drip", "drive", "drop", "drum", "dry", "duck", "dune", "duty", "dwarf", "eagle", "early",
    "earth", "east", "echo", "edge", "egg", "eight", "elbow", "elder", "electric", "elephant",
    "else", "embark", "embrace", "emotion", "employ", "empty", "endless", "energy", "engage",
    "enhance", "enjoy", "enroll", "enter", "equal", "era", "erupt", "essay", "essence", "estate",
    "eternal", "ethics", "evolve", "example", "exchange", "excite", "exclude", "excuse", "execute",
    "exhibit", "exist", "exit", "exotic", "expand", "expect", "expire", "expose", "extend", "eye",
    "faith", "fall", "family", "fan", "fancy", "fat", "father", "fault", "feature", "feel",
    "female", "fence", "fetch", "fever", "few", "fiber", "figure", "file", "film", "filter",
    "find", "fine", "finger", "firm", "first", "flash", "flee", "flight", "flock", "floor",
    "fluid", "fly", "foam", "fog", "fold", "food", "forest", "fortune", "forum", "fossil", "frame",
    "fringe", "frog", "front", "frost", "fruit", "future", "galaxy", "garage", "garden", "garlic",
    "gas", "gate", "genuine", "gesture", "ghost", "giant", "gift", "ginger", "girl", "give",
    "glad", "glare", "glass", "glide", "globe", "gloom", "glory", "glove", "glow", "glue", "good",
    "goose", "gospel", "gossip", "govern", "grab", "grain", "grass", "gravity", "great", "grief",
    "group", "guide", "guilt", "hair", "half", "hammer", "hand", "happy", "harbor", "hard",
    "harvest", "hat", "head", "health", "heavy", "helmet", "help", "hen", "hero", "high", "hobby",
    "hockey", "hold", "hole", "holiday", "hollow", "honey", "horn", "horror", "horse", "hospital",
    "host", "hotel", "hour", "hover", "hub", "huge", "human", "humble", "hundred", "hurry", "hurt",
    "icon", "idea", "identify", "idle", "ignore", "ill", "illegal", "illness", "image", "impact",
    "improve", "impulse", "inch", "include", "income", "increase", "indicate", "inform", "initial",
    "inner", "innocent", "input", "inspire", "install", "invest", "invite", "involve", "island",
    "isolate", "item", "ivory", "jacket", "jealous", "jeans", "jelly", "job", "join", "joke",
    "journey", "joy", "judge", "juice", "jump", "junk", "just", "key", "kind", "kiss", "kitten",
    "know", "lab", "label", "labor", "lady", "lamp", "language", "large", "later", "laundry",
    "lava", "law", "layer", "leader", "leaf", "learn", "length", "lens", "lesson", "letter",
    "level", "liar", "library", "life", "lift", "link", "lion", "liquid", "list", "little", "loan",
    "loop", "loud", "lounge", "love", "loyal", "lucky", "luxury", "machine", "mad", "magic",
    "maid", "mail", "main", "major", "make", "mammal", "mandate", "mango", "mansion", "manual",
    "marble", "market", "mask", "match", "matrix", "maximum", "mean", "meat", "medal", "melt",
    "member", "mention", "merit", "message", "method", "middle", "mimic", "mind", "minimum",
    "minor", "miracle", "mirror", "miss", "mix", "mixed", "mixture", "mobile", "modify", "moment",
    "monitor", "monkey", "monster", "month", "moon", "moral", "mother", "motion", "mountain",
    "move", "movie", "muscle", "mushroom", "music", "must", "mutual", "mystery", "name", "nasty",
    "nature", "near", "neck", "need", "negative", "neither", "nerve", "nest", "net", "network",
    "neutral", "never", "news", "night", "noble", "noodle", "north", "nothing", "novel", "now",
    "nuclear", "number", "nurse", "nut", "obscure", "observe", "occur", "ocean", "offer", "office",
    "oil", "okay", "olympic", "omit", "once", "one", "onion", "online", "only", "open", "opera",
    "opinion", "oppose", "option", "orange", "orbit", "order", "orient", "original", "ostrich",
    "outdoor", "output", "oval", "over", "oyster", "ozone", "pair", "panda", "panel", "panic",
    "paper", "parade", "parent", "parrot", "party", "patch", "path", "pattern", "pause", "pave",
    "peace", "peanut", "pear", "peasant", "pelican", "pen", "people", "pepper", "permit", "phrase",
    "physical", "picnic", "piece", "pigeon", "pilot", "pink", "pioneer", "pipe", "pistol", "pitch",
    "pizza", "plate", "play", "please", "plug", "plunge", "poem", "poet", "point", "polar", "pond",
    "pool", "popular", "position", "possible", "potato", "powder", "power", "praise", "predict",
    "prepare", "pretty", "pride", "print", "prison", "prize", "process", "produce", "program",
    "proof", "property", "prosper", "protect", "provide", "public", "pull", "pulse", "punch",
    "purchase", "purpose", "push", "pyramid", "quality", "quarter", "quick", "quit", "quote",
    "rabbit", "race", "rack", "rail", "rain", "raise", "rally", "ranch", "rapid", "rare", "rate",
    "rather", "razor", "rebel", "recall", "receive", "record", "reduce", "reflect", "reform",
    "region", "regret", "regular", "reject", "relax", "release", "relief", "rely", "remember",
    "render", "renew", "rent", "reopen", "repair", "repeat", "report", "require", "resist",
    "resource", "result", "retire", "retreat", "return", "reunion", "reveal", "reward", "rice",
    "rich", "ride", "rifle", "right", "rigid", "ring", "riot", "ripple", "rival", "road", "roast",
    "robot", "roof", "rose", "rotate", "round", "rubber", "rude", "run", "rural", "sad", "saddle",
    "safe", "salad", "salt", "salute", "sample", "sand", "satisfy", "sauce", "sausage", "save",
    "scan", "scare", "scene", "scheme", "school", "science", "scissors", "screen", "script",
    "scrub", "sea", "season", "seat", "second", "section", "seek", "select", "sell", "seminar",
    "sense", "series", "service", "session", "setup", "seven", "shadow", "shallow", "share",
    "shed", "shell", "shift", "shine", "ship", "short", "shrug", "shy", "sibling", "side", "sight",
    "sign", "silent", "silk", "silly", "silver", "since", "sing", "sister", "six", "skate",
    "sketch", "ski", "skill", "skirt", "skull", "slab", "sleep", "slight", "slogan", "slot",
    "slow", "small", "smart", "smile", "smoke", "smooth", "snack", "snake", "snap", "sniff",
    "soap", "soccer", "sock", "soda", "soldier", "solid", "solution", "solve", "song", "soon",
    "sort", "soul", "sound", "soup", "source", "space", "spare", "speak", "speed", "spend",
    "sphere", "spider", "spike", "spin", "spirit", "split", "spoil", "spoon", "spot", "spread",
    "square", "squeeze", "squirrel", "stadium", "stamp", "stand", "start", "state", "stay",
    "steel", "stem", "step", "stereo", "still", "stock", "stone", "stool", "story", "stove",
    "street", "strike", "strong", "stumble", "style", "subject", "submit", "sudden", "suffer",
    "suggest", "suit", "summer", "sun", "super", "supply", "supreme", "surface", "surround",
    "swallow", "swap", "swarm", "swear", "sweet", "swim", "swing", "symptom", "system", "table",
    "tag", "tail", "talent", "tank", "tape", "taste", "teach", "team", "term", "test", "text",
    "thank", "that", "theme", "then", "there", "they", "thing", "this", "three", "throw", "thumb",
    "ticket", "tide", "tiger", "timber", "time", "tiny", "tissue", "title", "tobacco", "today",
    "toe", "together", "toilet", "token", "tomato", "tone", "tongue", "tooth", "torch", "tornado",
    "toss", "total", "tourist", "toward", "tower", "town", "track", "train", "trap", "trash",
    "tray", "treat", "tree", "trial", "tribe", "trick", "trophy", "truly", "trumpet", "try",
    "tuition", "tumble", "tuna", "tunnel", "turtle", "twenty", "twice", "twist", "two", "type",
    "ugly", "umbrella", "unaware", "uncover", "under", "unfair", "unfold", "unhappy", "unit",
    "universe", "upgrade", "uphold", "upper", "upset", "usage", "use", "used", "useless", "usual",
    "utility", "vague", "valley", "vehicle", "velvet", "vendor", "venture", "venue", "verb",
    "verify", "very", "viable", "video", "view", "village", "virtual", "virus", "visit", "visual",
    "vocal", "voice", "void", "volcano", "volume", "voyage", "wage", "wagon", "wait", "wall",
    "walnut", "want", "warm", "wash", "waste", "way", "weapon", "web", "wedding", "weekend",
    "weird", "welcome", "west", "wet", "whale", "wheel", "where", "whisper", "width", "wife",
    "wild", "will", "window", "wine", "wing", "wink", "winner", "winter", "wire", "wise", "wish",
    "witness", "wolf", "woman", "wonder", "wood", "wool", "word", "worth", "wrist", "write",
    "wrong", "yard", "year", "yellow", "young", "youth", "zero", "zon",
];
